# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160613_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
